### ISSUE TITLE
Enquiry regarding types of url allowed.

### ISSUE THREAD

**Issue by xrainxfallx** [Kagami/tistore#2]
Is it possible to allow downloading from sites that do not have ".tistory.com" in the URL but the pictures on the web page are from "https://t1.daumcdn.net/cfile/tistory/xxxxxxxx"?

Example of this picture "https://t1.daumcdn.net/cfile/tistory/23071C4F583283411E?original" is from "http://oncefor2wice.com/13?category=708321"

**Comment by Kagami** [comment]
Yea, I think it's worth to allow any sites, not just the ones ending with `.tistory.com`.

**Comment by xrainxfallx** [comment]
Ah okay thank you! Just asking that this current version doesn't allow sites without .tistory.com to work yet right? 


P.S. I love you for this. Made my life easier to compile photos.

**Comment by Kagami** [comment]
Please try v0.4.0

**Comment by xrainxfallx** [comment]
Thank you so much! It works perfectly!
