### ISSUE TITLE
tistore v0.4.0 cannot always download any tistory page

### ISSUE THREAD

**Issue by Lumerica** [Kagami/tistore#3]
Hi,

There are several tistory pages I tried to download, a few works but a few just don't seem to work, for example:

http://karaworld.tistory.com/

After selecting a folder (no special characters) and entering the url the status bar says "crawling", soon it will just change statusbar to:

Add/crawl some links. Saving to: xxx

I am running windows 10 64 bit, but I don't think this is the issue because I have no problems downloading some other tistory sites.

Aside from this, is it possible to add the ability for the tool to automatically create folders based on page name and save the images there?

Thank you for putting so much time in this

**Comment by Kagami** [comment]
Thanks for the report, I will look into it.
Yea, creating page folders should be a good idea in case of grabbing big tistory blogs.

**Comment by Kagami** [comment]
Please try latest 0.5.0 release.

**Comment by Lumerica** [comment]
Hi thank you very much for the quick resolution, the problem has been resolved. :)

Sorry for nitpicking, but I just have one more question about the subdir creation. It looks like it creates sub directory based on page number.
Would it be possible to make it that the directories created are the title of the post or maybe dates?

**Comment by Kagami** [comment]
Yes, it's possible, I've created issue #4 for that.
